# Generated by Django 5.0.14 on 2026-08-04 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataRetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('retention_years', models.PositiveIntegerField(default=7, help_text='How long audit/evidence records are retained before purge-eligibility.')),
                ('data_residency_region', models.CharField(choices=[('sa', 'Saudi Arabia (KSA)'), ('eu', 'European Union'), ('us', 'United States')], default='sa', max_length=2)),
                ('pdpl_compliant', models.BooleanField(default=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retention_policy', to='core.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
