# Generated by Django 5.0.14 on 2026-08-04 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_dataretentionpolicy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmembership',
            options={'ordering': ['id']},
        ),
    ]
