# Generated by Django 5.0.14 on 2026-08-06 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_projectmembership_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('consultant', 'Consultant'), ('project_manager', 'Project Manager'), ('designer', 'Designer'), ('admin', 'Admin')], max_length=20),
        ),
    ]
