# Generated by Django 5.0.14 on 2026-08-06 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_projectmembership_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic'), ('ur', 'Urdu'), ('hi', 'Hindi')], default='en', max_length=2),
        ),
    ]
