# Generated by Django 5.0.14 on 2026-08-04 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=32)),
                ('sla_deadline', models.DateTimeField(blank=True, null=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('subject_type', models.CharField(default='general', max_length=64)),
                ('subject_ref', models.CharField(blank=True, max_length=128)),
                ('high_stakes', models.BooleanField(default=False)),
                ('hearing_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('understanding_text', models.TextField(blank=True)),
                ('understanding_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('agreement_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('agreement_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('assigned_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fallback_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='core.project')),
                ('understanding_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sla_deadline'],
            },
        ),
        migrations.CreateModel(
            name='DecisionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raci_role', models.CharField(choices=[('R', 'Responsible'), ('A', 'Accountable'), ('C', 'Consulted'), ('I', 'Informed')], max_length=1)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='approvals.decision')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EscalationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_sla_hours', models.PositiveIntegerField(default=48)),
                ('high_stakes_sla_hours', models.PositiveIntegerField(default=24)),
                ('fallback_role', models.CharField(default='owner', max_length=20)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_rule', to='core.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='decision',
            index=models.Index(fields=['project', 'status'], name='approvals_d_project_985b24_idx'),
        ),
        migrations.AddIndex(
            model_name='decision',
            index=models.Index(fields=['status', 'sla_deadline'], name='approvals_d_status_48611e_idx'),
        ),
        migrations.AddIndex(
            model_name='decisionparticipant',
            index=models.Index(fields=['user', 'raci_role'], name='approvals_d_user_id_b16e83_idx'),
        ),
        migrations.AddConstraint(
            model_name='decisionparticipant',
            constraint=models.UniqueConstraint(fields=('decision', 'user'), name='one_raci_row_per_user_per_decision'),
        ),
        migrations.AddConstraint(
            model_name='decisionparticipant',
            constraint=models.UniqueConstraint(condition=models.Q(('raci_role', 'A')), fields=('decision',), name='one_accountable_per_decision'),
        ),
    ]
