# Generated by Django 5.0.14 on 2026-08-06 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='scope',
            field=models.CharField(choices=[('owner', 'Owner (full project data)'), ('consultant', 'Consultant'), ('project_manager', 'Project Manager'), ('designer', 'Designer')], max_length=20),
        ),
    ]
