# Generated by Django 5.0.14 on 2026-08-04 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinationThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location_tag', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordination_threads', to='core.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoordinationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='rfi_change_control.coordinationthread')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=32)),
                ('sla_deadline', models.DateTimeField(blank=True, null=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('authority', models.CharField(default='Balady', max_length=100)),
                ('permit_number', models.CharField(blank=True, max_length=64)),
                ('current_as_of', models.DateTimeField()),
                ('assigned_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permits', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='QualityCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=32)),
                ('sla_deadline', models.DateTimeField(blank=True, null=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('milestone_ref', models.CharField(blank=True, max_length=128)),
                ('location_tag', models.CharField(blank=True, max_length=100)),
                ('assigned_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_checkpoints', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='RFI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=32)),
                ('sla_deadline', models.DateTimeField(blank=True, null=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('number', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('question', models.TextField()),
                ('response', models.TextField(blank=True)),
                ('schedule_impact_days', models.PositiveIntegerField(default=0, help_text='Schedule slip if this RFI goes unanswered by the SLA deadline.')),
                ('location_tag', models.CharField(blank=True, max_length=100)),
                ('assigned_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfis', to='core.project')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sla_deadline'],
            },
        ),
        migrations.CreateModel(
            name='Submittal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=32)),
                ('sla_deadline', models.DateTimeField(blank=True, null=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('spec_section', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('revision_number', models.PositiveIntegerField(default=1)),
                ('current_as_of', models.DateTimeField(help_text='Revision timestamp - mandatory on every versioned document view.')),
                ('assigned_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submittals', to='core.project')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=32)),
                ('sla_deadline', models.DateTimeField(blank=True, null=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('material', models.CharField(max_length=255)),
                ('supplier_name', models.CharField(max_length=255)),
                ('committed_date', models.DateField()),
                ('assigned_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_deliveries', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='ChangeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=32)),
                ('sla_deadline', models.DateTimeField(blank=True, null=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('baseline_scope', models.TextField()),
                ('scope_delta', models.TextField()),
                ('cost_impact', models.DecimalField(decimal_places=2, max_digits=12)),
                ('schedule_impact_days', models.IntegerField()),
                ('evidence_ref', models.CharField(blank=True, help_text='Pointer to a trust_evidence EvidenceRecord or equivalent.', max_length=255)),
                ('assigned_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_orders', to='core.project')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'status'], name='rfi_change__project_0dc7b5_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='coordinationthread',
            index=models.Index(fields=['project', 'location_tag'], name='rfi_change__project_5e1f80_idx'),
        ),
        migrations.AddIndex(
            model_name='permit',
            index=models.Index(fields=['project', 'status'], name='rfi_change__project_ca419e_idx'),
        ),
        migrations.AddIndex(
            model_name='qualitycheckpoint',
            index=models.Index(fields=['project', 'status'], name='rfi_change__project_4d5ab8_idx'),
        ),
        migrations.AddIndex(
            model_name='rfi',
            index=models.Index(fields=['project', 'status'], name='rfi_change__project_97246e_idx'),
        ),
        migrations.AddConstraint(
            model_name='rfi',
            constraint=models.UniqueConstraint(fields=('project', 'number'), name='unique_rfi_number_per_project'),
        ),
        migrations.AddIndex(
            model_name='submittal',
            index=models.Index(fields=['project', 'status'], name='rfi_change__project_e2fd15_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierdelivery',
            index=models.Index(fields=['project', 'status'], name='rfi_change__project_00e4ec_idx'),
        ),
    ]
