# Generated by Django 5.0.14 on 2026-08-04 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=10)),
                ('source', models.CharField(help_text="Which signal category raised this, e.g. 'integration_health', 'sla_compliance', 'security'.", max_length=64)),
                ('message', models.CharField(max_length=500)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['severity', 'acknowledged'], name='observabili_severit_141034_idx')],
            },
        ),
        migrations.CreateModel(
            name='DigestOpenEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digest_opens', to='core.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'created_at'], name='observabili_project_c64bfe_idx')],
            },
        ),
        migrations.CreateModel(
            name='IntegrationHealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration_type', models.CharField(choices=[('whatsapp_session', 'WhatsApp session'), ('email_oauth', 'Email OAuth'), ('government_portal', 'Government portal (Balady)')], max_length=32)),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('down', 'Down')], default='healthy', max_length=16)),
                ('last_checked_at', models.DateTimeField(auto_now=True)),
                ('last_error', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('project', models.ForeignKey(blank=True, help_text='Null for a platform-wide integration (e.g. a shared government-portal connector).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integration_health_checks', to='core.project')),
            ],
            options={
                'indexes': [models.Index(fields=['integration_type', 'status'], name='observabili_integra_ec8b24_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='integrationhealthcheck',
            constraint=models.UniqueConstraint(fields=('project', 'integration_type'), name='one_health_row_per_project_integration'),
        ),
    ]
