# Generated by Django 5.0.14 on 2026-08-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("observability", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="integrationhealthcheck",
            constraint=models.UniqueConstraint(
                condition=models.Q(("project__isnull", True)),
                fields=("integration_type",),
                name="one_health_row_per_platform_integration",
            ),
        ),
    ]
