# Generated by Django 5.0.14 on 2026-08-06 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_address', models.EmailField(max_length=254)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField()),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('connected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_account', to='core.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gmail_message_id', models.CharField(max_length=64)),
                ('gmail_thread_id', models.CharField(blank=True, max_length=64)),
                ('from_address', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('snippet', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('rfi', 'Request for Information'), ('submittal', 'Submittal / Shop Drawing'), ('payment', 'Payment Application'), ('safety', 'Safety & Hazard Alert'), ('general', 'General')], default='general', max_length=16)),
                ('requires_action', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField()),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_messages', to='core.project')),
                ('read_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['project', 'received_at'], name='email_integ_project_d81795_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='emailmessage',
            constraint=models.UniqueConstraint(fields=('project', 'gmail_message_id'), name='one_row_per_gmail_message'),
        ),
    ]
