# Generated by Django 5.0.14 on 2026-08-05 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='drawing_models/%Y/%m/')),
                ('format', models.CharField(choices=[('obj', 'obj'), ('3ds', '3ds'), ('dae', 'dae'), ('fbx', 'fbx'), ('lwo', 'lwo'), ('stl', 'stl'), ('ply', 'ply'), ('gltf', 'gltf'), ('glb', 'glb'), ('usd', 'usd'), ('usdz', 'usdz')], max_length=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawing_models', to='core.project')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project'], name='drawings_st_project_873027_idx')],
            },
        ),
    ]
