# Generated by Django 5.0.14 on 2026-08-05 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('contract_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='SAR', max_length=3)),
                ('scope_baseline', models.TextField(help_text='Baseline scope of work the contract value covers.')),
                ('source_file', models.FileField(blank=True, null=True, upload_to='contracts/%Y/%m/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under review'), ('approved', 'Approved'), ('superseded', 'Superseded'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('plain_arabic_summary', models.TextField(blank=True, help_text="Owner-friendly Arabic summary of payment schedule, warranty period, and scope boundaries - same pattern as owner-dashboard's drawing/spec summary layer.")),
                ('retention_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Percentage of each milestone payment withheld as retention until the decennial liability window.', max_digits=5)),
                ('ceiling_threshold_percentage', models.DecimalField(decimal_places=2, default=10, help_text='Cumulative spend (paid + approved change orders) beyond this % over contract_value triggers a ceiling alert.', max_digits=5)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='ContractAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('summary', models.TextField()),
                ('decision_id', models.PositiveIntegerField(blank=True, help_text='approvals.Decision.id routing the signature.', null=True)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='contract_amendments/%Y/%m/')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='contract_payments.contract')),
            ],
            options={
                'ordering': ['version_number'],
            },
        ),
        migrations.CreateModel(
            name='LegalAgentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_ref', models.CharField(help_text='e.g. "contract:14:payment_schedule" or "zatca-fatoora-compliance.md"', max_length=255)),
                ('content', models.TextField()),
                ('embedding', models.JSONField(blank=True, default=None, null=True)),
                ('embedding_model', models.CharField(blank=True, max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_agent_documents', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('due_condition', models.TextField(help_text='e.g. "40% structural completion"')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('retention_held', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('released', 'Released')], default='pending', max_length=20)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_milestones', to='contract_payments.contract')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_milestones', to='core.project')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zatca_status', models.CharField(choices=[('not_configured', 'Not configured'), ('pending_submission', 'Pending submission'), ('cleared', 'Cleared'), ('rejected', 'Rejected')], default='not_configured', max_length=20)),
                ('xml_payload', models.TextField(blank=True, help_text='UBL 2.1 XML - populated once ZATCA integration is implemented.')),
                ('qr_code_data', models.TextField(blank=True)),
                ('submitted_to_zatca_at', models.DateTimeField(blank=True, null=True)),
                ('milestone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='contract_payments.paymentmilestone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['project', 'status'], name='contract_pa_project_a075de_idx'),
        ),
        migrations.AddConstraint(
            model_name='contractamendment',
            constraint=models.UniqueConstraint(fields=('contract', 'version_number'), name='unique_amendment_version_per_contract'),
        ),
        migrations.AddIndex(
            model_name='legalagentdocument',
            index=models.Index(fields=['project'], name='contract_pa_project_ad5f7c_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmilestone',
            index=models.Index(fields=['project', 'status'], name='contract_pa_project_58bff0_idx'),
        ),
    ]
