# Generated by Django 5.0.14 on 2026-08-05 15:24

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('contract_payments', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        # Supabase Postgres ships this extension pre-authorized; CREATE
        # EXTENSION IF NOT EXISTS is idempotent so this is also safe to run
        # against a local dev DB that already has it installed via brew.
        VectorExtension(),
        # RemoveField + AddField rather than AlterField: Postgres has no
        # built-in jsonb -> vector cast, so a straight ALTER COLUMN ... TYPE
        # ... USING errors out regardless of row count. This table predates
        # any real deployment, so dropping and recreating the column is
        # safe here - it would NOT be safe once real embeddings exist in it.
        migrations.RemoveField(
            model_name='legalagentdocument',
            name='embedding',
        ),
        migrations.AddField(
            model_name='legalagentdocument',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True),
        ),
        migrations.AddIndex(
            model_name='legalagentdocument',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='legal_agent_doc_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
    ]
