# Generated by Django 5.0.14 on 2026-08-04 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('trust_evidence', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_type', models.CharField(max_length=64)),
                ('subject_id', models.CharField(max_length=64)),
                ('caption', models.CharField(max_length=255)),
                ('media_url', models.URLField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('captured_at', models.DateTimeField()),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='SilenceFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_type', models.CharField(max_length=64)),
                ('subject_id', models.CharField(max_length=64)),
                ('expected_by', models.DateTimeField()),
                ('flagged_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-flagged_at'],
            },
        ),
        migrations.RenameField(
            model_name='auditevent',
            old_name='metadata',
            new_name='payload',
        ),
        migrations.AddField(
            model_name='auditevent',
            name='actor_role',
            field=models.CharField(blank=True, choices=[('owner', 'Owner'), ('investor', 'Investor'), ('consultant', 'Consultant'), ('contractor', 'Contractor'), ('subcontractor', 'Subcontractor'), ('foreman', 'Foreman'), ('laborer', 'Laborer'), ('pmc', 'PMC'), ('san3_staff', 'San3 staff'), ('system', 'System')], max_length=20),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='channel',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('voice_call', 'Voice call'), ('platform_ui', 'Platform UI'), ('system', 'System')], default='platform_ui', max_length=20),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='source_message_ref',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='core.project'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['actor'], name='trust_evide_actor_i_f72cb4_idx'),
        ),
        migrations.AddField(
            model_name='evidencerecord',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_records', to='core.project'),
        ),
        migrations.AddField(
            model_name='evidencerecord',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evidencerecord',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='silenceflag',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='silence_flags', to='core.project'),
        ),
        migrations.AddIndex(
            model_name='evidencerecord',
            index=models.Index(fields=['subject_type', 'subject_id'], name='trust_evide_subject_a50fc3_idx'),
        ),
        migrations.AddIndex(
            model_name='silenceflag',
            index=models.Index(fields=['project', 'resolved'], name='trust_evide_project_9d1462_idx'),
        ),
        migrations.AddConstraint(
            model_name='silenceflag',
            constraint=models.UniqueConstraint(condition=models.Q(('resolved', False)), fields=('subject_type', 'subject_id'), name='one_open_silence_flag_per_subject'),
        ),
    ]
