# Generated by Django 5.0.14 on 2026-08-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("trust_evidence", "0002_evidencerecord_silenceflag_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="silenceflag",
            name="one_open_silence_flag_per_subject",
        ),
        migrations.AddConstraint(
            model_name="silenceflag",
            constraint=models.UniqueConstraint(
                condition=models.Q(("resolved", False)),
                fields=("project", "subject_type", "subject_id"),
                name="one_open_silence_flag_per_subject",
            ),
        ),
    ]
