# Generated by Django 5.0.14 on 2026-08-06 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trust_evidence', '0003_remove_silenceflag_one_open_silence_flag_per_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='actor_role',
            field=models.CharField(blank=True, choices=[('owner', 'Owner'), ('investor', 'Investor'), ('consultant', 'Consultant'), ('contractor', 'Contractor'), ('subcontractor', 'Subcontractor'), ('foreman', 'Foreman'), ('laborer', 'Laborer'), ('pmc', 'PMC'), ('san3_staff', 'Truepoint staff'), ('system', 'System')], max_length=20),
        ),
    ]
