# Generated by Django 5.0.14 on 2026-08-06 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trust_evidence', '0004_alter_auditevent_actor_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='actor_role',
            field=models.CharField(blank=True, choices=[('owner', 'Owner'), ('consultant', 'Consultant'), ('project_manager', 'Project Manager'), ('designer', 'Designer'), ('subcontractor', 'Subcontractor'), ('foreman', 'Foreman'), ('laborer', 'Laborer'), ('pmc', 'PMC'), ('san3_staff', 'Truepoint staff'), ('system', 'System')], max_length=20),
        ),
    ]
